server:
  port: 8080

spring:
  application:
    name: customer
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/customer
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
        ddl-auto: update
    show-sql: 'true'
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    #host: 127.0.0.1
    #port: 5672
    addresses: localhost:5672
    username: guest
    password: guest

eureka:
  client:
    #service-url: localhost:8761
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${random.int}
    hostname: localhost

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key